CREATE TABLE [dbo].[student_class_courses] (
    [id]               VARCHAR (50)   CONSTRAINT [DF_student_class_courses_id] DEFAULT ([dbo].[fn_GenerateUUIDv7]()) NOT NULL,
    [code]             VARCHAR (50)   NULL,
    [course_id]        VARCHAR (50)   NOT NULL,
    [student_class_id] VARCHAR (50)   NOT NULL,
    [start_date]       DATETIME2 (7)  NOT NULL,
    [end_date]         DATETIME2 (7)  NOT NULL,
    [weight]           INT            DEFAULT ((1)) NOT NULL,
    [final_score]      NUMERIC (5, 2) NULL,
    [status]           VARCHAR (20)   DEFAULT ('ENROLLED') NULL,
    [is_active]        BIT            DEFAULT ((1)) NOT NULL,
    [is_deleted]       BIT            DEFAULT ((0)) NOT NULL,
    [created_at]       DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [updated_at]       DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [created_by]       VARCHAR (50)   NULL,
    [updated_by]       VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_student_class_courses_assignment] UNIQUE ([course_id], [student_class_id]),
    CONSTRAINT [CK_student_class_courses_weight] CHECK ([weight] > (0)),
    CONSTRAINT [CK_student_class_courses_score] CHECK ([final_score] IS NULL OR ([final_score] >= (0) AND [final_score] <= (100))),
    CONSTRAINT [CK_student_class_courses_dates] CHECK ([end_date] >= [start_date]),
    CONSTRAINT [FK_student_class_courses_courses] FOREIGN KEY ([course_id]) REFERENCES [dbo].[courses] ([id]),
    CONSTRAINT [FK_student_class_courses_student_classes] FOREIGN KEY ([student_class_id]) REFERENCES [dbo].[student_classes] ([id]),
    CONSTRAINT [FK_student_class_courses_created_by] FOREIGN KEY ([created_by]) REFERENCES [dbo].[users] ([id]),
    CONSTRAINT [FK_student_class_courses_updated_by] FOREIGN KEY ([updated_by]) REFERENCES [dbo].[users] ([id])
);
