CREATE TABLE [dbo].[student_classes] (
    [id]          VARCHAR (50)   CONSTRAINT [DF_student_classes_id] DEFAULT ([dbo].[fn_GenerateUUIDv7]()) NOT NULL,
    [code]        VARCHAR (50)   NULL,
    [class_id]    VARCHAR (50)   NOT NULL,
    [student_id]  VARCHAR (50)   NOT NULL,
    [start_date]  DATETIME2 (7)  NOT NULL,
    [end_date]    DATETIME2 (7)  NOT NULL,
    [final_score] NUMERIC (5, 2) NULL,
    [supervisor]  NVARCHAR (100) NULL,
    [status]      VARCHAR (20)   DEFAULT ('ACTIVE') NOT NULL,
    [is_active]   BIT            DEFAULT ((1)) NOT NULL,
    [is_deleted]  BIT            DEFAULT ((0)) NOT NULL,
    [created_at]  DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [updated_at]  DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [created_by]  VARCHAR (50)   NULL,
    [updated_by]  VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_student_classes_enrollment] UNIQUE ([class_id], [student_id]),
    CONSTRAINT [CK_student_classes_score] CHECK ([final_score] IS NULL OR ([final_score] >= (0) AND [final_score] <= (10))),
    CONSTRAINT [CK_student_classes_dates] CHECK ([end_date] >= [start_date]),
    CONSTRAINT [FK_student_classes_classes] FOREIGN KEY ([class_id]) REFERENCES [dbo].[classes] ([id]),
    CONSTRAINT [FK_student_classes_users] FOREIGN KEY ([student_id]) REFERENCES [dbo].[users] ([id]),
    CONSTRAINT [FK_student_classes_created_by] FOREIGN KEY ([created_by]) REFERENCES [dbo].[users] ([id]),
    CONSTRAINT [FK_student_classes_updated_by] FOREIGN KEY ([updated_by]) REFERENCES [dbo].[users] ([id])
);
