version: '3.8'

services:
  # UniCore-authentication-redis:
  #   image: redis:7-alpine
  #   container_name: UniCore-authentication-redis
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - UniCore-network

  UniCore-database:
    image: postgres:15-alpine
    container_name: UniCore-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - UniCore-network
  # UniCore-authentication-service:
  #   image: UniCore-authentication-service
  #   container_name: UniCore-authentication-service
  #   build:
  #     context: ..
  #     dockerfile: Authentication-Service/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
  #     - Database__ConnectionString=${Database__ConnectionString}
  #     - Redis__ConnectionString=${Redis__ConnectionString}
  #   ports:
  #     - "5142:5142"
  #   depends_on:
  #     - UniCore-authentication-database
  #   networks:
  #     - UniCore-network

volumes:
  db-data:

networks:
  UniCore-network:
    driver: bridge
